// A fully synthetic example resume (generated by the DocuTune dataset
// generator style - no real person's data).

export const SAMPLE_RESUME = `John Doe
Hyderabad, Telangana
Email: john.doe42@gmail.com | Phone: +91-9876543210

Summary
Machine Learning Engineer with 3 years of experience in machine learning and data engineering.

Experience
Machine Learning Engineer, Nova Analytics
June 2022 - Present
- Worked on NLP pipelines for production workloads
- Built and maintained data services
Data Analyst, Zenith Data Labs
Aug 2020 - May 2022
- Created dashboards and reports for analytics metrics
- Automated ETL workflows and reduced manual effort by 20%

Education
B.Tech in Computer Science
XYZ Institute of Technology (2016 - 2020)
CGPA: 8.4/10

Skills
Python, PyTorch, SQL, Docker, FastAPI, Pandas

Projects
- Resume Screening Tool - Technologies: Python, spaCy, FastAPI
  Built as a personal project using spaCy and FastAPI.

Certifications
- AWS Certified Developer - Associate - Amazon Web Services (2023)
`
